// PA GA Guide — realistic seed data.
// Hand-curated from public PA General Assembly info; bill numbers/topics
// are plausible but illustrative. Refresh would replace this from palegis.us.

window.LAST_SYNC = '2026-04-01T03:00:00Z';

window.LEGISLATORS = [
  // ── Senate ──
  { id: 'yaw',     chamber: 'S', name: 'Gene Yaw',                party: 'R', district: 23,  initials: 'GY',
    counties: ['Bradford','Lycoming','Sullivan','Susquehanna','Union'],
    role: 'Majority Caucus Secretary',
    committees: [{name:'Environmental Resources & Energy', role:'CHAIR'},{name:'Banking & Insurance'},{name:'Education'},{name:'Judiciary'}],
    office: { room: '362', building: 'Main Capitol', wing: 'East Wing', floor: 3 },
    phone: '(717) 787-3280', email: 'gyaw@pasen.gov',
    coop: true, coopDetail: '4 co-ops · Tri-County, Sullivan County, Claverack, Wellsboro',
    starred: true,
  },
  { id: 'phillipshill', chamber: 'S', name: 'Kristin Phillips-Hill', party: 'R', district: 28, initials: 'KP',
    counties: ['York'], role: 'Majority Whip',
    committees: [{name:'Communications & Technology', role:'CHAIR'},{name:'Appropriations'},{name:'Finance'}],
    office: { room: '362', building: 'Main Capitol', wing: 'East Wing', floor: 3 },
    phone: '(717) 787-6538', email: 'kphillipshill@pasen.gov', coop: false, starred: true,
  },
  { id: 'hutchinson', chamber: 'S', name: 'Scott Hutchinson', party: 'R', district: 21, initials: 'SH',
    counties: ['Butler','Forest','Venango','Warren'], role: 'Majority Caucus Chair',
    committees: [{name:'Finance', role:'CHAIR'},{name:'Banking'},{name:'Game & Fisheries'}],
    office: { room: '286', building: 'Main Capitol', wing: 'East Wing', floor: 2 },
    phone: '(717) 787-9684', email: 'shutchinson@pasen.gov',
    coop: true, coopDetail: '3 co-ops · Central Electric, Northwestern, United', starred: false,
  },
  { id: 'boscola', chamber: 'S', name: 'Lisa M. Boscola', party: 'D', district: 18, initials: 'LB',
    counties: ['Lehigh','Northampton','Monroe'], role: 'Democratic Caucus Secretary',
    committees: [{name:'State Government', role:'MIN. CHAIR'},{name:'Appropriations'},{name:'Education'}],
    office: { room: '535', building: 'Main Capitol', wing: 'East Wing', floor: 5 },
    phone: '(717) 787-4236', email: 'lboscola@pasenate.com', coop: false, starred: true,
  },
  { id: 'costa',   chamber: 'S', name: 'Jay Costa',               party: 'D', district: 43, initials: 'JC',
    counties: ['Allegheny'], role: 'Democratic Floor Leader',
    committees: [{name:'Rules & Executive Nominations'},{name:'Appropriations'},{name:'Finance'}],
    office: { room: '535', building: 'Main Capitol', wing: 'East Wing', floor: 5 },
    phone: '(717) 787-7683', email: 'jcosta@pasenate.com', coop: false, starred: false,
  },
  { id: 'argall', chamber: 'S', name: 'David G. Argall', party: 'R', district: 29, initials: 'DA',
    counties: ['Schuylkill','Carbon'], role: '',
    committees: [{name:'State Government', role:'CHAIR'},{name:'Education'}],
    office: { room: '171', building: 'Main Capitol', wing: 'North Office', floor: 1 },
    phone: '(717) 787-2637', email: 'dargall@pasen.gov', coop: true,
    coopDetail: '1 co-op · New Enterprise', starred: false,
  },
  { id: 'bartolotta', chamber: 'S', name: 'Camera Bartolotta', party: 'R', district: 46, initials: 'CB',
    counties: ['Beaver','Greene','Washington'], role: '',
    committees: [{name:'Labor & Industry', role:'CHAIR'},{name:'Banking'}],
    office: { room: '286', building: 'Main Capitol', wing: 'East Wing', floor: 2 },
    phone: '(717) 787-1463', email: 'cbartolotta@pasen.gov', coop: true,
    coopDetail: '2 co-ops · Tri-County, Allegheny', starred: false,
  },

  // ── House ──
  { id: 'causer', chamber: 'H', name: 'Martin T. Causer', party: 'R', district: 67, initials: 'MC',
    counties: ['Cameron','McKean','Potter'], role: 'Republican Whip',
    committees: [{name:'Agriculture & Rural Affairs', role:'MIN. CHAIR'},{name:'Game & Fisheries'},{name:'Consumer Affairs'}],
    office: { room: '413', building: 'Main Capitol', wing: 'East Wing', floor: 4 },
    phone: '(717) 772-9908', email: 'mcauser@pahousegop.com',
    coop: true, coopDetail: '2 co-ops · Tri-County, Warren Electric',
    starred: true,
  },
  { id: 'nelson',  chamber: 'H', name: 'Eric R. Nelson',          party: 'R', district: 57, initials: 'EN',
    counties: ['Westmoreland'], role: '',
    committees: [{name:'Consumer Affairs'},{name:'Insurance'},{name:'Liquor Control'}],
    office: { room: '423', building: 'Irvis Office Bldg', wing: '', floor: 4 },
    phone: '(717) 260-6144', email: 'enelson@pahousegop.com',
    coop: true, coopDetail: '1 co-op · Westmoreland Rural', starred: true,
  },
  { id: 'kim', chamber: 'H', name: 'Patty Kim', party: 'D', district: 103, initials: 'PK',
    counties: ['Dauphin'], role: '',
    committees: [{name:'Children & Youth'},{name:'Tourism & Recreational Development'}],
    office: { room: '108', building: 'Irvis Office Bldg', wing: '', floor: 1 },
    phone: '(717) 783-1610', email: 'pkim@pahouse.net', coop: false, starred: false,
  },
  { id: 'struzzi', chamber: 'H', name: 'James Struzzi', party: 'R', district: 62, initials: 'JS',
    counties: ['Indiana'], role: '',
    committees: [{name:'Consumer Affairs', role:'MIN. CHAIR'},{name:'Transportation'}],
    office: { room: '422', building: 'Irvis Office Bldg', wing: '', floor: 4 },
    phone: '(717) 705-1923', email: 'jstruzzi@pahousegop.com',
    coop: true, coopDetail: '1 co-op · REA Energy', starred: false,
  },
  { id: 'matzie', chamber: 'H', name: 'Robert F. Matzie', party: 'D', district: 16, initials: 'RM',
    counties: ['Allegheny','Beaver'], role: 'Consumer Affairs Cmte CHAIR',
    committees: [{name:'Consumer Affairs', role:'CHAIR'},{name:'Liquor Control'}],
    office: { room: '38B', building: 'East Wing', wing: '', floor: 'EB' },
    phone: '(717) 787-4444', email: 'rmatzie@pahouse.net', coop: false, starred: true,
  },
];

// Bills indexed by sponsor id. Format: { num, title, role, status, statusKind, rea, topic, lastAction }
window.BILLS_BY_SPONSOR = {
  yaw: [
    { num:'SB 832', title:'Net-metering caps update for distributed generation', role:'PRIME', status:'Reported out of cmte', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 18' },
    { num:'SB 401', title:'Forestry tax stability for sustainably-managed timberland', role:'PRIME', status:'In Finance Cmte', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Mar 22' },
    { num:'SB 277', title:'Rural broadband expansion via co-op fiber', role:'CO-SPONSOR', status:'Second consideration', statusKind:'go', rea:true, topic:'Telecom', lastAction:'Apr 09' },
    { num:'SB 119', title:'Rural emergency communications grants', role:'CO-SPONSOR', status:'Passed Senate 47-3', statusKind:'go', rea:true, topic:'Telecom', lastAction:'Mar 28' },
    { num:'SB 88',  title:'Cooperative governance modernization', role:'PRIME', status:'In Banking Cmte', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Feb 14' },
    { num:'SR 12',  title:'Recognizing Pennsylvania electric cooperatives', role:'PRIME', status:'Adopted', statusKind:'go', rea:true, topic:'Energy', lastAction:'Mar 03' },
    { num:'SB 712', title:'Watershed restoration grants', role:'PRIME', status:'In Env. Resources', statusKind:'wait', rea:false, topic:'Energy', lastAction:'Apr 02' },
  ],
  causer: [
    { num:'HB 1024', title:'Rural broadband co-op grants (PA Rural Broadband Act)', role:'PRIME', status:'In Consumer Affairs', statusKind:'wait', rea:true, topic:'Telecom', lastAction:'Apr 22' },
    { num:'HB 873',  title:'Right-of-way clearance standards for utilities', role:'CO-SPONSOR', status:'Passed House 168-32', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 15' },
    { num:'HB 412',  title:'Net-metering update for distributed generation', role:'CO-SPONSOR', status:'Reported out of Cons. Affairs', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 09' },
    { num:'HB 388',  title:'Agricultural tax credit expansion', role:'PRIME', status:'First consideration', statusKind:'wait', rea:false, topic:'Ag', lastAction:'Mar 28' },
    { num:'HR 88',   title:'Resolution honoring PA electric cooperatives', role:'PRIME', status:'Adopted', statusKind:'go', rea:true, topic:'Energy', lastAction:'Mar 03' },
    { num:'HB 251',  title:'Vegetation management standards for distribution lines', role:'CO-SPONSOR', status:'In Cons. Affairs', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Feb 28' },
    { num:'HB 567',  title:'Game lands access for rural landowners', role:'PRIME', status:'In Game & Fisheries', statusKind:'wait', rea:false, topic:'Ag', lastAction:'Feb 12' },
  ],
  phillipshill: [
    { num:'SB 624', title:'Statewide broadband mapping authority', role:'PRIME', status:'In Communications', statusKind:'wait', rea:false, topic:'Telecom', lastAction:'Apr 18' },
    { num:'SB 277', title:'Rural broadband expansion via co-op fiber', role:'PRIME', status:'Second consideration', statusKind:'go', rea:true, topic:'Telecom', lastAction:'Apr 09' },
    { num:'SB 412', title:'Tax-credit transparency reporting', role:'CO-SPONSOR', status:'In Finance', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Mar 22' },
  ],
  hutchinson: [
    { num:'SB 92',  title:'Property-tax relief for senior homeowners', role:'PRIME', status:'In Finance', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Apr 11' },
    { num:'SB 832', title:'Net-metering caps update for distributed generation', role:'CO-SPONSOR', status:'Reported out of cmte', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 18' },
  ],
  boscola: [
    { num:'SB 198', title:'Open meetings transparency reform', role:'PRIME', status:'In State Govt', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Apr 02' },
    { num:'SB 277', title:'Rural broadband expansion via co-op fiber', role:'CO-SPONSOR', status:'Second consideration', statusKind:'go', rea:true, topic:'Telecom', lastAction:'Apr 09' },
  ],
  costa: [
    { num:'SB 322', title:'Energy assistance program funding', role:'PRIME', status:'In Appropriations', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Apr 15' },
    { num:'SB 88',  title:'Cooperative governance modernization', role:'CO-SPONSOR', status:'In Banking', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Feb 14' },
  ],
  argall: [
    { num:'SB 156', title:'School property tax elimination', role:'PRIME', status:'In Finance', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Mar 14' },
  ],
  bartolotta: [
    { num:'SB 444', title:'Workforce apprenticeship grants', role:'PRIME', status:'Passed Senate', statusKind:'go', rea:false, topic:'Tax', lastAction:'Apr 01' },
    { num:'SB 277', title:'Rural broadband expansion via co-op fiber', role:'CO-SPONSOR', status:'Second consideration', statusKind:'go', rea:true, topic:'Telecom', lastAction:'Apr 09' },
  ],
  nelson: [
    { num:'HB 412', title:'Net-metering update for distributed generation', role:'PRIME', status:'Reported out of Cons. Affairs', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 09' },
    { num:'HB 251', title:'Vegetation management standards for distribution lines', role:'PRIME', status:'In Cons. Affairs', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Feb 28' },
    { num:'HB 1024', title:'Rural broadband co-op grants', role:'CO-SPONSOR', status:'In Consumer Affairs', statusKind:'wait', rea:true, topic:'Telecom', lastAction:'Apr 22' },
  ],
  kim:    [{ num:'HB 802', title:'Workforce housing tax credit', role:'PRIME', status:'In Finance', statusKind:'wait', rea:false, topic:'Tax', lastAction:'Apr 04' }],
  struzzi:[
    { num:'HB 251', title:'Vegetation management standards for distribution lines', role:'CO-SPONSOR', status:'In Cons. Affairs', statusKind:'wait', rea:true, topic:'Energy', lastAction:'Feb 28' },
    { num:'HB 444', title:'Truck weight limits on rural roads', role:'PRIME', status:'In Transportation', statusKind:'wait', rea:false, topic:'Ag', lastAction:'Mar 11' },
  ],
  matzie: [
    { num:'HB 412',  title:'Net-metering update for distributed generation', role:'CO-SPONSOR', status:'Reported out of Cons. Affairs', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 09' },
    { num:'HB 873',  title:'Right-of-way clearance standards for utilities', role:'PRIME', status:'Passed House', statusKind:'go', rea:true, topic:'Energy', lastAction:'Apr 15' },
  ],
};

// Committees seed — Senate + House standing committees most relevant to REA / co-ops.
// Members reference legislator ids in LEGISLATORS above; counts are illustrative.
window.COMMITTEES = [
  // ── Senate ──────────────────────────────────────────────
  { id: 'sen-envres', chamber: 'S', name: 'Environmental Resources & Energy', chair: 'yaw', minChair: 'boscola',
    members: ['yaw','hutchinson','costa','boscola','argall','bartolotta'],
    activeBills: ['SB 832','SB 712','SB 88','SB 451'] },
  { id: 'sen-comms', chamber: 'S', name: 'Communications & Technology', chair: 'phillipshill', minChair: 'costa',
    members: ['phillipshill','yaw','boscola','costa','argall'],
    activeBills: ['SB 624','SB 277','SB 119'] },
  { id: 'sen-conscom', chamber: 'S', name: 'Consumer Protection & Professional Licensure', chair: 'bartolotta', minChair: 'boscola',
    members: ['bartolotta','phillipshill','boscola','hutchinson'],
    activeBills: ['SB 504','SB 318'] },
  { id: 'sen-agrural', chamber: 'S', name: 'Agriculture & Rural Affairs', chair: 'argall', minChair: 'costa',
    members: ['argall','yaw','hutchinson','bartolotta','costa'],
    activeBills: ['SB 220','SB 145','SB 622'] },
  { id: 'sen-finance', chamber: 'S', name: 'Finance', chair: 'hutchinson', minChair: 'costa',
    members: ['hutchinson','phillipshill','costa','argall'],
    activeBills: ['SB 401','SB 99'] },
  { id: 'sen-banking', chamber: 'S', name: 'Banking & Insurance', chair: 'bartolotta', minChair: 'boscola',
    members: ['yaw','hutchinson','bartolotta','boscola'],
    activeBills: ['SB 712','SB 555'] },
  { id: 'sen-localgov', chamber: 'S', name: 'Local Government', chair: 'argall', minChair: 'costa',
    members: ['argall','phillipshill','costa','boscola'],
    activeBills: ['SB 333','SB 287'] },
  { id: 'sen-laborind', chamber: 'S', name: 'Labor & Industry', chair: 'bartolotta', minChair: 'costa',
    members: ['bartolotta','hutchinson','costa'],
    activeBills: ['SB 612','SB 188'] },
  { id: 'sen-stategov', chamber: 'S', name: 'State Government', chair: 'argall', minChair: 'boscola',
    members: ['argall','boscola','phillipshill'],
    activeBills: ['SB 102','SB 448'] },
  { id: 'sen-transport', chamber: 'S', name: 'Transportation', chair: 'phillipshill', minChair: 'costa',
    members: ['phillipshill','hutchinson','costa','bartolotta'],
    activeBills: ['SB 211','SB 76'] },
  { id: 'sen-approps', chamber: 'S', name: 'Appropriations', chair: 'phillipshill', minChair: 'costa',
    members: ['phillipshill','costa','boscola','hutchinson','argall'],
    activeBills: ['SB 1','SB 1100','SB 1101'] },
  { id: 'sen-rules', chamber: 'S', name: 'Rules & Executive Nominations', chair: 'costa', minChair: null,
    members: ['costa','phillipshill','hutchinson','boscola'],
    activeBills: [] },

  // ── House ───────────────────────────────────────────────
  { id: 'hse-consumer', chamber: 'H', name: 'Consumer Protection, Technology & Utilities', chair: 'matzie', minChair: 'struzzi',
    members: ['matzie','struzzi','nelson','causer','kim'],
    activeBills: ['HB 1024','HB 412','HB 251','HB 873'] },
  { id: 'hse-agrural', chamber: 'H', name: 'Agriculture & Rural Affairs', chair: 'kim', minChair: 'causer',
    members: ['causer','struzzi','nelson','kim','matzie'],
    activeBills: ['HB 388','HB 567','HB 1188'] },
  { id: 'hse-envres', chamber: 'H', name: 'Environmental Resources & Energy', chair: 'matzie', minChair: 'causer',
    members: ['matzie','causer','nelson','struzzi','kim'],
    activeBills: ['HB 902','HB 410','HB 117'] },
  { id: 'hse-commerce', chamber: 'H', name: 'Commerce', chair: 'matzie', minChair: 'nelson',
    members: ['matzie','nelson','struzzi','kim'],
    activeBills: ['HB 644','HB 219'] },
  { id: 'hse-insurance', chamber: 'H', name: 'Insurance', chair: 'kim', minChair: 'nelson',
    members: ['nelson','kim','struzzi'],
    activeBills: ['HB 712','HB 305'] },
  { id: 'hse-finance', chamber: 'H', name: 'Finance', chair: 'matzie', minChair: 'causer',
    members: ['matzie','causer','nelson','kim'],
    activeBills: ['HB 1101','HB 88'] },
  { id: 'hse-localgov', chamber: 'H', name: 'Local Government', chair: 'kim', minChair: 'struzzi',
    members: ['kim','struzzi','causer','nelson'],
    activeBills: ['HB 412','HB 1077'] },
  { id: 'hse-laborind', chamber: 'H', name: 'Labor & Industry', chair: 'matzie', minChair: 'nelson',
    members: ['matzie','nelson','kim'],
    activeBills: ['HB 533','HB 211'] },
  { id: 'hse-transport', chamber: 'H', name: 'Transportation', chair: 'struzzi', minChair: 'matzie',
    members: ['struzzi','causer','matzie','kim'],
    activeBills: ['HB 660','HB 144','HB 821'] },
  { id: 'hse-stategov', chamber: 'H', name: 'State Government', chair: 'kim', minChair: 'causer',
    members: ['kim','matzie','causer','nelson'],
    activeBills: ['HB 100','HB 1422'] },
  { id: 'hse-judiciary', chamber: 'H', name: 'Judiciary', chair: 'matzie', minChair: 'nelson',
    members: ['matzie','nelson','kim'],
    activeBills: ['HB 1014','HB 290'] },
  { id: 'hse-veterans', chamber: 'H', name: 'Veterans Affairs & Emergency Preparedness', chair: 'causer', minChair: 'kim',
    members: ['causer','struzzi','kim'],
    activeBills: ['HB 477','HB 902'] },
  { id: 'hse-approps', chamber: 'H', name: 'Appropriations', chair: 'matzie', minChair: 'causer',
    members: ['matzie','causer','nelson','kim','struzzi'],
    activeBills: ['HB 1','HB 1500','HB 1501'] },
  { id: 'hse-gameFish', chamber: 'H', name: 'Game & Fisheries', chair: 'causer', minChair: 'matzie',
    members: ['causer','struzzi','nelson'],
    activeBills: ['HB 622','HB 318'] },
];
